---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: check-ast
# Jupyter lints - annoying
# -   repo: https://github.com/nbQA-dev/nbQA
#     rev: 1.7.1
#     hooks:
#     -   id: nbqa-ruff
# YAML lint - annoying
# -   repo: https://github.com/adrienverge/yamllint.git
#     rev: v1.33.0
#     hooks:
#     -   id: yamllint
# Codespell - tagging french words as incorrect
# -   repo: https://github.com/codespell-project/codespell
#     rev: v2.2.6
#     hooks:
#     -   id: codespell
