---
services:
  transformers-notebook:
    # ./ specifies you will be using a Dockerfile in your directory to build off of
    build: ./
    ports:
      - 8000:8888
    environment:
      - JUPYTER_ALLOW_INSECURE_WRITES=true
    volumes:
      - ./:/home/jovyan
    command: "start-notebook.py --NotebookApp.token='' --NotebookApp.password=''"
